### ISSUE TITLE
Unstable startup

### ISSUE THREAD

**Issue by brutevinch** [MrPsi/NodeMCU-Wixel#11]
Sometimes system working strange - ping is ok but port 50005 closed. Just need restart. Have you this issue? I can't reproduce bug. It's random.

**Comment by MrPsi** [comment]
I have not had this issue. I have four nodes running and they have been working without problems for months at a time. The only reason they are being restarted is when we have some sort of power outage.

**Comment by brutevinch** [comment]
Ok i'll test it. Thx

**Comment by MrPsi** [comment]
I built another unit this week and I did indeed have a startup problem. It seemed like the startup code in init.lua does not run on first startup when power is connected. When I press reset on the NodeMCU it starts up fine and works as expected. I located the problem to the power connection to the Wixel. When the Wixel was connected it did not start up as expected. When I removed the power to the Wixel it started up fine. To solve the issue I just connected a transistor between the NodeMCU and the Wixel on the 3.3V connection, and connected the base of the transistor to another 3.3V output on the NodeMCU.

**Comment by brutevinch** [comment]
How do you saturate transistor? which part of code?

**Comment by MrPsi** [comment]
Did you get this to work for you?

I'm planning on changing the schema and code to delay the startup of the Wixel. But have not had time to do this yet.

**Comment by brutevinch** [comment]
Yeah. I've got this connection 5V->ams1117->wixel+esp12f
