### ISSUE TITLE
Do the SSID have a limitation of length?

### ISSUE THREAD

**Issue by ldkbyj** [MrPsi/NodeMCU-Wixel#12]
Hi,
I made a NodeMCU-Wixel which can connect to the wifi of my house using below configuration. 
local cfg = {
    ip = "192.168.25.35",
    netmask = "255.255.255.0",
    gateway = "192.168.25.1"
}
local wifiSsid = "SK_WiFi13B0"
local wifiPassword = "1312025315"

And I presented this H/W to my neighbor. But I could't connect to the wifi of her house using this H/W. I set the wifiSsid like below on this nodemcu , do the SSID have a limitation of length?
I cannot find any issue :(

local cfg = {
    ip = "172.30.1.101",
    netmask = "255.255.255.0",
    gateway = "172.30.1.254"
}
local wifiSsid = "olleh_GiGA_WiFi_FCF7"
local wifiPassword = "0000005855"
# Below is the output of connecting failure.

PORT OPEN 115200

Communication with MCU...
.......
PORT CLOSED

PORT OPEN 115200

Communication with MCU...
Got answer! AutoDetect firmware...
Communication with MCU established.
NodeMCU firmware detected.
=node.heap()
46600

> Uploading to ESP file init.lua...Success
> 
> Uploading to ESP file modClient.lua...Success
> 
> Uploading to ESP file modCompile.lua...Success
> 
> Uploading to ESP file modConverter.lua...Success
> Uploading to ESP file modInfo.lua...Success
> Uploading to ESP file modInitialize.lua...Success
> 
> Uploading to ESP file modLed.lua...Success
> 
> Uploading to ESP file modList.lua...Success
> 
> Uploading to ESP file modPrintText.lua...Success
> 
> Uploading to ESP file modSaveData.lua...Success
> 
> Uploading to ESP file modServer.lua...Success
> 
> Uploading to ESP file modStart.lua...Success
> 
> Uploading to ESP file modUart.lua...Success
> 
> Uploading to ESP file modWifi.lua...Success
> 
> Uploading to ESP file modWifiMon.lua...Success
> 
> PORT CLOSED

PORT OPEN 115200

Communication with MCU...
Got answer! AutoDetect firmware...
Communication with MCU established.
NodeMCU firmware detected.
=node.heap()
44168

> Connecting...
> Connecting...
> Connecting...
> Connecting...
> Connecting...
> Connecting...
> Wifi connection failed 3

**Comment by MrPsi** [comment]
Hi,

Sorry for late answer. I have been away on holiday.

The ssid is limited to 31 bytes. See http://nodemcu.readthedocs.io/en/dev/en/modules/wifi/#wifistaconfig
Error 3 means that the access point cannot be found. Did you enter the correct SSID?

**Comment by ldkbyj** [comment]
I will try again tomorrow. thanks a lot~~~~

**Comment by ldkbyj** [comment]
I found the root cause about above question, there are two WiFi( 1G bps and 100M bps) in that house.
NodeMCU cannot work with 1G bps WiFi, so I changed the WiFi to 100M bps. It works now :)
Thanks a lot.

**Comment by MrPsi** [comment]
Great that you got it working.
If you want, you can change the physical mode for the NodeMCU. Right now it is set to 802.11b, but you can change it to 802.11n by changing a line in modWifi.lua.

Change
`wifi.setphymode(wifi.PHYMODE_B)`
to
`wifi.setphymode(wifi.PHYMODE_N)`

802.11b gives maximum range, 802.11n gives maximum speed.

See link for more info
http://nodemcu.readthedocs.io/en/dev/en/modules/wifi/#wifisetphymode
