### ISSUE TITLE
NodeMCU modules

### ISSUE THREAD

**Issue by shelsgit** [MrPsi/NodeMCU-Wixel#18]
Hi, & thanks for sharing this/ love being able to see my nightscout #s all over the house without carrying my phone and receiver around.

I am attempting to learn how to program the ESP8266/NodeMCU, in an attempt to make a display to view my Nightscout #s with it, and a cheap I2C display (rather than running multiple phones or tablets, forcing them always on).  Then, if I ever figure it out, and possible, I would like to add it to your wixel/NodeMCU setup so I can have the one ESP8266 do both (send data to xdrip app and also download data from nightscout and display it on the display).  (Although my programming skills are currently at a not-much-more-than a 'hello world' level!!).

Would you please tell me the 10 modules used in your firmware (Or if there's a better way to figuring this out, other than going through each of your .lua files and looking for each function and which module it's called from would you please let me know).

Thank you

**Comment by MrPsi** [comment]
Hi,

Sounds like a fun project. I hope you will get it working soon.

The modules I'm using are the following: cjson,file,gpio,net,node,rtctime,sntp,tmr,uart,wifi.
You will see the modules listed during boot if you are connected to the NodeMCU with ESplorer or similar.

Regards

**Comment by shelsgit** [comment]
Thank you!
