### ISSUE TITLE
Unable to communicate with wixel

### ISSUE THREAD

**Issue by rmsryu** [MrPsi/NodeMCU-Wixel#21]
Hi MrPsi,

I've followed the instructions, and it doesn't seems to be communication between the wixel and the nodeMCU. If connected to the wixel with usb cable I can see the readings from the dexcom coming through COM5 port,  but I would expect to see the same print in the  COM6 when connected to the nodeMCU 
`modPrintText.print("Uart received '" .. trimmedLine .. "'")`  I've changed `allowPrint = true` so I thought I would see something.

My config settings are the ones that you have by default

Wixel UART @ 9600 bauds
NodeMCU 
`uart.setup(0, 9600, 8, uart.PARITY_NONE, uart.STOPBITS_1, 0)` `uart.alt(1)` I've also tried with standards RX TX, and it's the same result. The monitor never display anything in "Last Data" cell.

Do you know what could be wrong?

Edited: See below wires and connections
![20170522_222335](https://cloud.githubusercontent.com/assets/4973612/26330958/72281d16-3f46-11e7-9554-bf55f46de222.jpg)

**Comment by MrPsi** [comment]
Hi,

After a look at your connections it looks like you are missing a cable for the grounding of the Wixel.
Also the led circuit seems wrong. The resistor should be connected to ground. Now it looks like it is connection to P2_1 on the Wixel.

**Comment by rmsryu** [comment]
oops... I didn't realize of the angle of the picture make that perspective. I had to put extensions in the used pins of the wixel  because this breadboard is quite sort I couldn't fit both boards.. I have another one in somewhere but I couldn't find it.

Anyway I think this wixel is faulty. When is powered via the vin pin at 3.3v from the nodeMCU the yellow leds doesn't even start flashing. Only works when is powered via usb. When usb is connected I can't get readings into the nodeMCU, I only can see it in my computer :(. I think I might order a new one.

![20170530_214303](https://cloud.githubusercontent.com/assets/4973612/26604462/676338ba-4582-11e7-983b-bf39374c2b33.jpg)

**Comment by MrPsi** [comment]
Alright, now I see how it looks like :)
But don't you still need to bridge the left and the right part of the ground circuit? 
Like you have done for the 3.3V connection.
![circuit](https://cloud.githubusercontent.com/assets/17367370/26710256/d8996310-4758-11e7-991f-f70c7d220ce0.png)

**Comment by rmsryu** [comment]
Not required in this breadboard, check the black painted line (vs the red), I tested all the circuit with the multimeter and all seems ok. 3.3v comes fine to the vin pin. I think I should close this issue, until I get a new wixel. 

Thanks for your help.
