### ISSUE TITLE
xdrip not showing any bg value

### ISSUE THREAD

**Issue by danpowell88** [MrPsi/NodeMCU-Wixel#6]
I've got everything setup and xdrip is just showing ?AD, it appears the values are coming across correctly

```
Starting NodeMCU Wixel in 10 seconds...
> Connecting...
Connecting...
Wifi connected 192.168.1.178
Uart received '6726272 160768 151872 214 -58 221 3028'
Server received '{"numberOfRecords":200,"version":1}
'
Uart received '6726272 148608 148992 215 -71 225 0'
Server received '{"numberOfRecords":1,"version":1}
'
Uart received '6726272 147968 149248 215 -67 229 0'
Server received '{"numberOfRecords":1,"version":1}
'
Uart received '6726272 149184 150528 215 -83 233 0'
Server received '{"numberOfRecords":1,"version":1}
'
```

Any ideas?

**Comment by MrPsi** [comment]
The communication looks correct. First it requests 200 records, which is the maximum value. The next time it requests 1 record, which indicates that xDrip has received the previous record.
Seems to be an issue with xDrip. Have you started a new sensor? Has it asked you to enter calibrations?

**Comment by danpowell88** [comment]
The sensor was started a few days ago and I back dated its start when starting xdrip, all of the values received in that test (on a standalone xdrip tablet instance) were only from the wifi wixels.

I did another test on my xdrip phone instance (that I use with xbridge) and it appears to work correctly, it seems like the problem is with xdrip but I'm not sure exactly what it is yet.

Will raise an issue with the devs there

**Comment by MrPsi** [comment]
Good thing it worked on the other phone. Don't know why it did not work on the tablet.
If you want to see the actual values sent from the node you can connect to it with a terminal (like PuTTY) and send {"numberOfRecords":200,"version":1}. It will send back a maximum of five values read from the wixel.

**Comment by danpowell88** [comment]
It ended up working on both, not sure what the root cause was.

I've tried sending the command to through putty but not having much luck, putty just closes and I dont see anything.

What settings should i use? RAW, 115200/9600? and then paste that line and press enter?

**Comment by MrPsi** [comment]
Use Raw, also select Never for "Close window on exit". Enter ip and port and click Open. Then just paste the line and press enter. Should work.
